---
- name: ansible-role-generate-self-signed-cert
  hosts: localhost
  gather_facts: yes #no

  tasks:
    - include_role:
        name: "../ansible-role-generate-self-signed-cert"
      vars:
        cert_commonName: "*.dev.tortuga.systems"
        san_dns:
          - { index: 1, dns: ip-10-15-12-59.ec2.internal}
          - { index: 2, dns: ip-10-15-12-59..dev.tortuga.systems}
        san_ip:
          - { index: 1, ip: 10.15.12.59}
